[meta]
name = "ItemExchange"
author = "RuteNL"
category = "TMX"
siteid = 164
perms = "paid"

version = "1.1.6"

[script]
imports = [ "Permissions.as", "Formatting.as", "Dialogs.as" ]
exports = [ "src/Exports/Export.as" ]
timeout = 5000